exclude: "node_modules|servicems/public/frontend/assets|frappe-semgrep-rules"
default_stages: [pre-commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
      - id: no-commit-to-branch
        args:
          - --branch
          - main
          - --branch
          - master
          - --branch
          - develop
          - --branch
          - version-15
          - --branch
          - version-15-hotfix

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff
        name: "Run ruff linter and apply fixes"
        args: ["--fix"]
        files: "^servicems/.*\\.py$"
      - id: ruff-format
        name: "Format Python code"
        files: "^servicems/.*\\.py$"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types_or: [javascript, vue, css, scss, json]
        files: "^(frontend|servicems)/.*"
        exclude: |
          (?x)^(
              frontend/dist/.*|
              servicems/public/frontend/assets/.*|
              .*node_modules.*|
              .*boilerplate.*
          )$
        stages: [manual]

  - repo: local
    hooks:
      - id: frappe-semgrep
        name: semgrep (frappe rules)
        entry: bash -c 'if [ ! -d frappe-semgrep-rules/.git ]; then rm -rf frappe-semgrep-rules && GIT_TEMPLATE_DIR="" git clone --depth 1 https://github.com/frappe/semgrep-rules.git frappe-semgrep-rules; fi && semgrep scan --config ./frappe-semgrep-rules/rules --error --skip-unknown-extensions --quiet "$@"' --
        language: python
        additional_dependencies: ["semgrep"]
        types_or: [python, javascript]
        pass_filenames: true
        require_serial: true

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, refactor, chore, docs, style, test, ci, perf, build, revert]

ci:
  autoupdate_schedule: weekly
  skip: [frappe-semgrep]
  submodules: false
