[project]
name = "servicems"
authors = [
    { name = "Aakvatech Limited", email = "info@aakvatech.com" }
]
description = "Service Management System for ERPNext"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # "frappe" # Installed and managed by bench.
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0,<17.0.0"

[tool.ruff]
line-length = 110
target-version = "py310"

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "I",
    "UP",
    "B",
]
ignore = [
    "E101",
    "E402",
    "E501",
    "E741",
    "W191",
    "UP009",
    "UP010",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = true
